#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Ranged_FringePlank_Athena_V2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "PhysicsCore_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Prj_Ranged_FringePlank_Athena_V2.B_Prj_Ranged_FringePlank_Athena_V2_C
// 0x03B8 (0x0C80 - 0x08C8)
class AB_Prj_Ranged_FringePlank_Athena_V2_C final : public AFortProjectileBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      NS_Emote_SingAlong_Book;                           // 0x08D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               GiantFlare;                                        // 0x08D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_SurfaceTypeSoundComponent_C*        BP_SurfaceTypeSoundComponent;                      // 0x08E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortCollisionAudioComponent*           FortCollisionAudio;                                // 0x08E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        LoopingAudioTell;                                  // 0x08F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               P_GL_Ribbon_SmokeTrail;                            // 0x08F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Mesh;                                              // 0x0900(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         DestroyedMesh_MeshScale_7DE468DA415445BB12465FB06BC9FC9A; // 0x0908(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            DestroyedMesh__Direction_7DE468DA415445BB12465FB06BC9FC9A; // 0x090C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_90D[0x3];                                      // 0x090D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     DestroyedMesh;                                     // 0x0910(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         VelocityAndGravityLerp_VelocityCurve_A7409B354D16857784EA3C8FCB6D7A14; // 0x0918(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            VelocityAndGravityLerp__Direction_A7409B354D16857784EA3C8FCB6D7A14; // 0x091C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91D[0x3];                                      // 0x091D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     VelocityAndGravityLerp;                            // 0x0920(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        RibbonTrail_PS;                                    // 0x0928(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               RibbonTrail_PSC;                                   // 0x0930(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        DeathExplosion_PS;                                 // 0x0938(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        WaterImpact_PS;                                    // 0x0940(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Bounce_Sound;                                      // 0x0948(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           BounceCueTag;                                      // 0x0950(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         Initial_Speed;                                     // 0x0958(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Final_XYSpeedMultiplier;                           // 0x0980(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         DisableMarkingPlayers;                             // 0x09A8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         CurrentBounces;                                    // 0x09D0(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          isSlowing;                                         // 0x09D4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9D5[0x3];                                      // 0x09D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         GravityAfterBounced;                               // 0x09D8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          InWater;                                           // 0x0A00(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A01[0x7];                                      // 0x0A01(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystem*                        SparkExplosion_PS;                                 // 0x0A08(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SparkExplosionSize;                                // 0x0A10(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A14[0x4];                                      // 0x0A14(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 FireMeshBGA;                                       // 0x0A18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 spark;                                             // 0x0A20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             HitWater_Sound;                                    // 0x0A28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             SparkExplosion_Sound;                              // 0x0A30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         NumSparksToDrop;                                   // 0x0A38(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         TimeBeforeSparkExplosion;                          // 0x0A60(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         SparkSpeed;                                        // 0x0A88(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         SparkGravityScale;                                 // 0x0AB0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         GravityAfterParachute;                             // 0x0AD8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FVector                                Lerp_StartVel;                                     // 0x0B00(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B0C[0x4];                                      // 0x0B0C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         MaxBounces;                                        // 0x0B10(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         ChuteAngleInterpSpeed;                             // 0x0B38(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShootSparksInCone;                                 // 0x0B3C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B3D[0x3];                                      // 0x0B3D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Lerp_StartXYSpeed;                                 // 0x0B40(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Lerp_FinalXYSpeed;                                 // 0x0B44(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Lerp_StartZSpeed;                                  // 0x0B48(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Lerp_XYDirection;                                  // 0x0B4C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CachedRandomSparkOffsetAngle;                      // 0x0B58(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Impact_Point;                                      // 0x0B5C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Impact_Sound;                                      // 0x0B68(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Parachute_Audio;                                   // 0x0B70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Parachute_Disapears;                               // 0x0B78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MarkActorInt;                                      // 0x0B80(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B84[0x4];                                      // 0x0B84(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystem*                        IndicatedPS;                                       // 0x0B88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   ParticleSystemParamName;                           // 0x0B90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                PSOffset;                                          // 0x0B98(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                PSDBNOOffset;                                      // 0x0BA4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   PSVectorParamName;                                 // 0x0BB0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 IndicatorGroup;                                    // 0x0BB8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class AAthena_PlayerController_C*             AthenaPlayerControler;                             // 0x0BC8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CurrentMarkingRadius;                              // 0x0BD0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                OriginalParachuteScale;                            // 0x0BD4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         Initial_Gravity;                                   // 0x0BE0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTag                           CueOnMark;                                         // 0x0C08(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          MarkPlayers;                                       // 0x0C10(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C11[0x3];                                      // 0x0C11(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MaxMarkRaycastDistance;                            // 0x0C14(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MinMarkRadius;                                     // 0x0C18(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaxMarkRadius;                                     // 0x0C1C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SparksCurrentlySpawned;                            // 0x0C20(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          isDying;                                           // 0x0C24(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C25[0x3];                                      // 0x0C25(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         MarkingRange;                                      // 0x0C28(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         SF_IndicatorDuration;                              // 0x0C50(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UClass*                                 GE_Indicator_Marked;                               // 0x0C78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__WaterInteractionComponent_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature(class AFortWaterBodyActor* WaterBody, class UFortWaterInteractionComponent* WaterInteractionComponent_0, bool bIsFirstBody);
	void DestroyedMesh__FinishedFunc();
	void DestroyedMesh__UpdateFunc();
	void DetroySelf();
	void DropMultipleSparks(int32 Number, const struct FVector& Location);
	void DropSingleSpark(float Rotation, const struct FVector& Location);
	void DropSparksOnWater();
	void ExecuteUbergraph_B_Prj_Ranged_FringePlank_Athena_V2(int32 EntryPoint);
	void GetActorsInRange(TArray<class AFortPlayerPawn*>& Array, TArray<class AFortPlayerPawn*>* Result_);
	void HaltVelocityCurve();
	void HitWaterEffects();
	void IncrementBounces();
	void MarkEnemies_();
	void OnBounce(const struct FHitResult& Hit);
	void OnStop(const struct FHitResult& Hit);
	void Play_Impact_Sound();
	void ReceiveBeginPlay();
	void ReceiveDestroyed();
	void SendOutPing();
	void SetInitialProjectileValues();
	void SlowSpeed();
	void SparkAndSlowDown();
	void SparkExplosion();
	void SpawnBounceFX(struct FHitResult& Hit);
	void UserConstructionScript();
	void VelocityAndGravityLerp__FinishedFunc();
	void VelocityAndGravityLerp__UpdateFunc();
	void WaterBounce();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Prj_Ranged_FringePlank_Athena_V2_C">();
	}
	static class AB_Prj_Ranged_FringePlank_Athena_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Prj_Ranged_FringePlank_Athena_V2_C>();
	}
};
static_assert(alignof(AB_Prj_Ranged_FringePlank_Athena_V2_C) == 0x000008, "Wrong alignment on AB_Prj_Ranged_FringePlank_Athena_V2_C");
static_assert(sizeof(AB_Prj_Ranged_FringePlank_Athena_V2_C) == 0x000C80, "Wrong size on AB_Prj_Ranged_FringePlank_Athena_V2_C");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, UberGraphFrame) == 0x0008C8, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, NS_Emote_SingAlong_Book) == 0x0008D0, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::NS_Emote_SingAlong_Book' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, GiantFlare) == 0x0008D8, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::GiantFlare' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, BP_SurfaceTypeSoundComponent) == 0x0008E0, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::BP_SurfaceTypeSoundComponent' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, FortCollisionAudio) == 0x0008E8, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::FortCollisionAudio' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, LoopingAudioTell) == 0x0008F0, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::LoopingAudioTell' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, P_GL_Ribbon_SmokeTrail) == 0x0008F8, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::P_GL_Ribbon_SmokeTrail' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Mesh) == 0x000900, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Mesh' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, DestroyedMesh_MeshScale_7DE468DA415445BB12465FB06BC9FC9A) == 0x000908, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::DestroyedMesh_MeshScale_7DE468DA415445BB12465FB06BC9FC9A' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, DestroyedMesh__Direction_7DE468DA415445BB12465FB06BC9FC9A) == 0x00090C, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::DestroyedMesh__Direction_7DE468DA415445BB12465FB06BC9FC9A' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, DestroyedMesh) == 0x000910, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::DestroyedMesh' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, VelocityAndGravityLerp_VelocityCurve_A7409B354D16857784EA3C8FCB6D7A14) == 0x000918, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::VelocityAndGravityLerp_VelocityCurve_A7409B354D16857784EA3C8FCB6D7A14' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, VelocityAndGravityLerp__Direction_A7409B354D16857784EA3C8FCB6D7A14) == 0x00091C, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::VelocityAndGravityLerp__Direction_A7409B354D16857784EA3C8FCB6D7A14' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, VelocityAndGravityLerp) == 0x000920, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::VelocityAndGravityLerp' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, RibbonTrail_PS) == 0x000928, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::RibbonTrail_PS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, RibbonTrail_PSC) == 0x000930, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::RibbonTrail_PSC' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, DeathExplosion_PS) == 0x000938, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::DeathExplosion_PS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, WaterImpact_PS) == 0x000940, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::WaterImpact_PS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Bounce_Sound) == 0x000948, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Bounce_Sound' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, BounceCueTag) == 0x000950, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::BounceCueTag' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Initial_Speed) == 0x000958, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Initial_Speed' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Final_XYSpeedMultiplier) == 0x000980, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Final_XYSpeedMultiplier' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, DisableMarkingPlayers) == 0x0009A8, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::DisableMarkingPlayers' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, CurrentBounces) == 0x0009D0, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::CurrentBounces' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, isSlowing) == 0x0009D4, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::isSlowing' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, GravityAfterBounced) == 0x0009D8, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::GravityAfterBounced' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, InWater) == 0x000A00, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::InWater' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, SparkExplosion_PS) == 0x000A08, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::SparkExplosion_PS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, SparkExplosionSize) == 0x000A10, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::SparkExplosionSize' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, FireMeshBGA) == 0x000A18, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::FireMeshBGA' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, spark) == 0x000A20, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::spark' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, HitWater_Sound) == 0x000A28, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::HitWater_Sound' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, SparkExplosion_Sound) == 0x000A30, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::SparkExplosion_Sound' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, NumSparksToDrop) == 0x000A38, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::NumSparksToDrop' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, TimeBeforeSparkExplosion) == 0x000A60, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::TimeBeforeSparkExplosion' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, SparkSpeed) == 0x000A88, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::SparkSpeed' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, SparkGravityScale) == 0x000AB0, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::SparkGravityScale' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, GravityAfterParachute) == 0x000AD8, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::GravityAfterParachute' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Lerp_StartVel) == 0x000B00, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Lerp_StartVel' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, MaxBounces) == 0x000B10, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::MaxBounces' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, ChuteAngleInterpSpeed) == 0x000B38, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::ChuteAngleInterpSpeed' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, ShootSparksInCone) == 0x000B3C, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::ShootSparksInCone' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Lerp_StartXYSpeed) == 0x000B40, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Lerp_StartXYSpeed' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Lerp_FinalXYSpeed) == 0x000B44, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Lerp_FinalXYSpeed' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Lerp_StartZSpeed) == 0x000B48, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Lerp_StartZSpeed' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Lerp_XYDirection) == 0x000B4C, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Lerp_XYDirection' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, CachedRandomSparkOffsetAngle) == 0x000B58, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::CachedRandomSparkOffsetAngle' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Impact_Point) == 0x000B5C, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Impact_Point' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Impact_Sound) == 0x000B68, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Impact_Sound' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Parachute_Audio) == 0x000B70, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Parachute_Audio' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Parachute_Disapears) == 0x000B78, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Parachute_Disapears' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, MarkActorInt) == 0x000B80, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::MarkActorInt' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, IndicatedPS) == 0x000B88, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::IndicatedPS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, ParticleSystemParamName) == 0x000B90, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::ParticleSystemParamName' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, PSOffset) == 0x000B98, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::PSOffset' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, PSDBNOOffset) == 0x000BA4, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::PSDBNOOffset' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, PSVectorParamName) == 0x000BB0, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::PSVectorParamName' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, IndicatorGroup) == 0x000BB8, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::IndicatorGroup' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, AthenaPlayerControler) == 0x000BC8, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::AthenaPlayerControler' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, CurrentMarkingRadius) == 0x000BD0, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::CurrentMarkingRadius' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, OriginalParachuteScale) == 0x000BD4, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::OriginalParachuteScale' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, Initial_Gravity) == 0x000BE0, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::Initial_Gravity' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, CueOnMark) == 0x000C08, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::CueOnMark' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, MarkPlayers) == 0x000C10, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::MarkPlayers' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, MaxMarkRaycastDistance) == 0x000C14, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::MaxMarkRaycastDistance' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, MinMarkRadius) == 0x000C18, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::MinMarkRadius' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, MaxMarkRadius) == 0x000C1C, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::MaxMarkRadius' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, SparksCurrentlySpawned) == 0x000C20, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::SparksCurrentlySpawned' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, isDying) == 0x000C24, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::isDying' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, MarkingRange) == 0x000C28, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::MarkingRange' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, SF_IndicatorDuration) == 0x000C50, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::SF_IndicatorDuration' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_FringePlank_Athena_V2_C, GE_Indicator_Marked) == 0x000C78, "Member 'AB_Prj_Ranged_FringePlank_Athena_V2_C::GE_Indicator_Marked' has a wrong offset!");

}

