#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BGA_Athena_ShieldGenerator_NonPhysics

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature final
{
public:
	class AFortWaterBodyActor*                    WaterBody;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortWaterInteractionComponent*         WaterInteractionComponent;                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsFirstBody;                                      // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature) == 0x000008, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature) == 0x000018, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature, WaterBody) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature::WaterBody' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature, WaterInteractionComponent) == 0x000008, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature::WaterInteractionComponent' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature, bIsFirstBody) == 0x000010, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature::bIsFirstBody' has a wrong offset!");

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature final
{
public:
	class AFortWaterBodyActor*                    WaterBody;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortWaterInteractionComponent*         WaterInteractionComponent;                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsLastBody;                                       // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature) == 0x000008, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature) == 0x000018, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature, WaterBody) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature::WaterBody' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature, WaterInteractionComponent) == 0x000008, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature::WaterInteractionComponent' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature, bIsLastBody) == 0x000010, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_BndEvt__BGA_Athena_ShieldGenerator_NonPhysics_FortWaterInteraction_K2Node_ComponentBoundEvent_1_WaterInteractionOnExitWater__DelegateSignature::bIsLastBody' has a wrong offset!");

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics
// 0x08A0 (0x08A0 - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_Damage;                               // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  K2Node_Event_DamageTags;                           // 0x0008(0x0020)(ConstParm)
	struct FVector                                K2Node_Event_Momentum;                             // 0x0028(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_HitInfo;                              // 0x0034(0x009C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AController*                            K2Node_Event_InstigatedBy;                         // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_DamageCauser;                         // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           K2Node_Event_EffectContext;                        // 0x00E0(0x0018)()
	EFortBuildingInitializationReason             K2Node_Event_InitializationReason;                 // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortBuildingPersistentState                  K2Node_Event_BuildingPersistentState;              // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FA[0x2];                                       // 0x00FA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetValueAtLevel_ReturnValue;              // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValueAtLevel_ReturnValue_1;            // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_HitResult;                            // 0x0104(0x009C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FGameplayCueParameters                 CallFunc_MakeGameplayCueParametersFromHitResult_ReturnValue; // 0x01A0(0x00C0)(ContainsInstancedReference)
	class AFortWaterBodyActor*                    K2Node_ComponentBoundEvent_WaterBody_1;            // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortWaterInteractionComponent*         K2Node_ComponentBoundEvent_WaterInteractionComponent_1; // 0x0268(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsFirstBody;           // 0x0270(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_271[0x7];                                      // 0x0271(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_EffectContextGetInstigatorActor_ReturnValue; // 0x0278(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0280(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x02B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x02BC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x02C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D4[0x4];                                      // 0x02D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 CallFunc_MakeGameplayCueParameters_ReturnValue;    // 0x02D8(0x00C0)(ContainsInstancedReference)
	uint8                                         Pad_398[0x8];                                      // 0x0398(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue_1;               // 0x03A0(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location_1;                // 0x03D0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation_1;                // 0x03DC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale_1;                   // 0x03E8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F4[0x4];                                      // 0x03F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_EffectContextGetInstigatorActor_ReturnValue_1; // 0x03F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 CallFunc_MakeGameplayCueParameters_ReturnValue_1;  // 0x0400(0x00C0)(ContainsInstancedReference)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x04C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawnAthena*                  K2Node_DynamicCast_AsFort_Player_Pawn_Athena;      // 0x04C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x04D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x04D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4D2[0x6];                                      // 0x04D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x04D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerControllerAthena*            K2Node_DynamicCast_AsFort_Player_Controller_Athena; // 0x04E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x04E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E9[0x7];                                      // 0x04E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaMarkerComponent*                 CallFunc_GetMarkerComponent_ReturnValue;           // 0x04F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMarkerID                              CallFunc_MarkActorOnClient_ReturnValue;            // 0x04F8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FActiveGameplayEffectHandle            CallFunc_ApplyGlobalEnvironmentGameplayEffectToActor_ReturnValue; // 0x0500(0x0008)(NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_Actor;                                // 0x0508(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_Event_HitComp;                              // 0x0510(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0518(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x051C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_CustomEvent_ServerLocation;                 // 0x0520(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x052C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52D[0x3];                                      // 0x052D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult;       // 0x0530(0x009C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue;          // 0x05CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5CD[0x3];                                      // 0x05CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue_2;               // 0x05D0(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0600(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_601[0x3];                                      // 0x0601(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakTransform_Location_2;                // 0x0604(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation_2;                // 0x0610(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale_2;                   // 0x061C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_628[0x8];                                      // 0x0628(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0630(0x0030)(IsPlainOldData, NoDestructor)
	class AFortWaterBodyActor*                    K2Node_CustomEvent_Water_Body;                     // 0x0660(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_IsInWater;                      // 0x0668(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_669[0x7];                                      // 0x0669(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0670(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWaterBodyComponent*                    CallFunc_GetWaterBodyComponent_ReturnValue;        // 0x0678(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AB_Decal_ShieldGenerator_C*             CallFunc_FinishSpawningActor_ReturnValue;          // 0x0680(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0688(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_689[0x3];                                      // 0x0689(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x068C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetWaterSurfaceInfo_WaterPlaneLocation;   // 0x0698(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetWaterSurfaceInfo_WaterPlaneNormal;     // 0x06A4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetWaterSurfaceInfo_WaterSurfacePosition; // 0x06B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetWaterSurfaceInfo_WaterDepth;           // 0x06BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetWaterSurfaceInfo_WaterBodyIdx;         // 0x06C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetWaterSurfaceInfo_WaterVelocity;        // 0x06C4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x06D0(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x06E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6E4[0x4];                                      // 0x06E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x06E8(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x06F0(0x0010)(ZeroConstructor, NoDestructor)
	class AFortWaterBodyActor*                    K2Node_ComponentBoundEvent_WaterBody;              // 0x0700(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortWaterInteractionComponent*         K2Node_ComponentBoundEvent_WaterInteractionComponent; // 0x0708(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsLastBody;            // 0x0710(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_711[0x3];                                      // 0x0711(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetValueAtLevel_ReturnValue_2;            // 0x0714(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x0718(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsCurieActive_ReturnValue;                // 0x0720(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x0721(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_722[0x2];                                      // 0x0722(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0724(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValueAtLevel_ReturnValue_3;            // 0x0730(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_2;        // 0x0734(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValueAtLevel_ReturnValue_4;            // 0x0740(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0744(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValueAtLevel_ReturnValue_5;            // 0x0748(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsCurieActive_ReturnValue_1;              // 0x074C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74D[0x3];                                      // 0x074D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0750(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_GetValueAtLevel_ReturnValue_6;            // 0x0760(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0764(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_765[0x3];                                      // 0x0765(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetValueAtLevel_ReturnValue_7;            // 0x0768(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x076C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_76D[0x3];                                      // 0x076D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_2;        // 0x0770(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0778(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0788(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue_1;        // 0x0789(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x078A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_78B[0x1];                                      // 0x078B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetValueAtLevel_ReturnValue_8;            // 0x078C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_3;        // 0x0790(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValueAtLevel_ReturnValue_9;            // 0x0798(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_StopDecalUpdates;               // 0x079C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x079D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79E[0x2];                                      // 0x079E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x07A0(0x0010)(ConstParm, ReferenceParm)
	TArray<class AActor*>                         CallFunc_SphereOverlapActors_OutActors;            // 0x07B0(0x0010)(ReferenceParm)
	bool                                          CallFunc_SphereOverlapActors_ReturnValue;          // 0x07C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C1[0x7];                                      // 0x07C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x07C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x07D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_MakeHitResult_ReturnValue;                // 0x07D4(0x009C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0870(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0871(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_872[0x2];                                      // 0x0872(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_3;        // 0x0874(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_4;        // 0x0880(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Vector_Distance_ReturnValue;              // 0x088C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_5;        // 0x0890(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics) == 0x000010, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics) == 0x0008A0, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, EntryPoint) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::EntryPoint' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_Damage) == 0x000004, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_Damage' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_DamageTags) == 0x000008, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_DamageTags' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_Momentum) == 0x000028, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_Momentum' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_HitInfo) == 0x000034, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_HitInfo' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_InstigatedBy) == 0x0000D0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_InstigatedBy' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_DamageCauser) == 0x0000D8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_DamageCauser' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_EffectContext) == 0x0000E0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_EffectContext' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_InitializationReason) == 0x0000F8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_InitializationReason' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_BuildingPersistentState) == 0x0000F9, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_BuildingPersistentState' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetValueAtLevel_ReturnValue) == 0x0000FC, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetValueAtLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetValueAtLevel_ReturnValue_1) == 0x000100, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetValueAtLevel_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_HitResult) == 0x000104, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_HitResult' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_MakeGameplayCueParametersFromHitResult_ReturnValue) == 0x0001A0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_MakeGameplayCueParametersFromHitResult_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_ComponentBoundEvent_WaterBody_1) == 0x000260, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_ComponentBoundEvent_WaterBody_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_ComponentBoundEvent_WaterInteractionComponent_1) == 0x000268, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_ComponentBoundEvent_WaterInteractionComponent_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_ComponentBoundEvent_bIsFirstBody) == 0x000270, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_ComponentBoundEvent_bIsFirstBody' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_EffectContextGetInstigatorActor_ReturnValue) == 0x000278, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_EffectContextGetInstigatorActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetTransform_ReturnValue) == 0x000280, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BreakTransform_Location) == 0x0002B0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BreakTransform_Rotation) == 0x0002BC, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BreakTransform_Scale) == 0x0002C8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_MakeGameplayCueParameters_ReturnValue) == 0x0002D8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_MakeGameplayCueParameters_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetTransform_ReturnValue_1) == 0x0003A0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BreakTransform_Location_1) == 0x0003D0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BreakTransform_Location_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BreakTransform_Rotation_1) == 0x0003DC, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BreakTransform_Rotation_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BreakTransform_Scale_1) == 0x0003E8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BreakTransform_Scale_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_EffectContextGetInstigatorActor_ReturnValue_1) == 0x0003F8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_EffectContextGetInstigatorActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_MakeGameplayCueParameters_ReturnValue_1) == 0x000400, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_MakeGameplayCueParameters_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetOwner_ReturnValue) == 0x0004C0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_DynamicCast_AsFort_Player_Pawn_Athena) == 0x0004C8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_DynamicCast_AsFort_Player_Pawn_Athena' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_DynamicCast_bSuccess) == 0x0004D0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, Temp_bool_IsClosed_Variable) == 0x0004D1, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetController_ReturnValue) == 0x0004D8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_DynamicCast_AsFort_Player_Controller_Athena) == 0x0004E0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_DynamicCast_AsFort_Player_Controller_Athena' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_DynamicCast_bSuccess_1) == 0x0004E8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetMarkerComponent_ReturnValue) == 0x0004F0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetMarkerComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_MarkActorOnClient_ReturnValue) == 0x0004F8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_MarkActorOnClient_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_ApplyGlobalEnvironmentGameplayEffectToActor_ReturnValue) == 0x000500, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_ApplyGlobalEnvironmentGameplayEffectToActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_Actor) == 0x000508, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_Actor' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_Event_HitComp) == 0x000510, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_Event_HitComp' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, Temp_int_Loop_Counter_Variable) == 0x000518, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_Add_IntInt_ReturnValue) == 0x00051C, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_CustomEvent_ServerLocation) == 0x000520, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_CustomEvent_ServerLocation' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, Temp_bool_Has_Been_Initd_Variable) == 0x00052C, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_SetActorLocation_SweepHitResult) == 0x000530, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_SetActorLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_SetActorLocation_ReturnValue) == 0x0005CC, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_SetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetTransform_ReturnValue_2) == 0x0005D0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetTransform_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_IsValid_ReturnValue) == 0x000600, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BreakTransform_Location_2) == 0x000604, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BreakTransform_Location_2' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BreakTransform_Rotation_2) == 0x000610, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BreakTransform_Rotation_2' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BreakTransform_Scale_2) == 0x00061C, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BreakTransform_Scale_2' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_MakeTransform_ReturnValue) == 0x000630, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_CustomEvent_Water_Body) == 0x000660, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_CustomEvent_Water_Body' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_CustomEvent_IsInWater) == 0x000668, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_CustomEvent_IsInWater' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000670, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetWaterBodyComponent_ReturnValue) == 0x000678, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetWaterBodyComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_FinishSpawningActor_ReturnValue) == 0x000680, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_HasAuthority_ReturnValue) == 0x000688, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_GetActorLocation_ReturnValue) == 0x00068C, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetWaterSurfaceInfo_WaterPlaneLocation) == 0x000698, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetWaterSurfaceInfo_WaterPlaneLocation' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetWaterSurfaceInfo_WaterPlaneNormal) == 0x0006A4, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetWaterSurfaceInfo_WaterPlaneNormal' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetWaterSurfaceInfo_WaterSurfacePosition) == 0x0006B0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetWaterSurfaceInfo_WaterSurfacePosition' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetWaterSurfaceInfo_WaterDepth) == 0x0006BC, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetWaterSurfaceInfo_WaterDepth' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetWaterSurfaceInfo_WaterBodyIdx) == 0x0006C0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetWaterSurfaceInfo_WaterBodyIdx' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetWaterSurfaceInfo_WaterVelocity) == 0x0006C4, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetWaterSurfaceInfo_WaterVelocity' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_CreateDelegate_OutputDelegate) == 0x0006D0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_Conv_IntToFloat_ReturnValue) == 0x0006E0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0006E8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_CreateDelegate_OutputDelegate_1) == 0x0006F0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_ComponentBoundEvent_WaterBody) == 0x000700, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_ComponentBoundEvent_WaterBody' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_ComponentBoundEvent_WaterInteractionComponent) == 0x000708, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_ComponentBoundEvent_WaterInteractionComponent' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_ComponentBoundEvent_bIsLastBody) == 0x000710, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_ComponentBoundEvent_bIsLastBody' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetValueAtLevel_ReturnValue_2) == 0x000714, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetValueAtLevel_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x000718, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_IsCurieActive_ReturnValue) == 0x000720, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_IsCurieActive_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_HasAuthority_ReturnValue_1) == 0x000721, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_HasAuthority_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000724, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetValueAtLevel_ReturnValue_3) == 0x000730, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetValueAtLevel_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_GetActorLocation_ReturnValue_2) == 0x000734, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_GetActorLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetValueAtLevel_ReturnValue_4) == 0x000740, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetValueAtLevel_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, Temp_int_Array_Index_Variable) == 0x000744, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetValueAtLevel_ReturnValue_5) == 0x000748, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetValueAtLevel_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_IsCurieActive_ReturnValue_1) == 0x00074C, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_IsCurieActive_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_CreateDelegate_OutputDelegate_2) == 0x000750, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetValueAtLevel_ReturnValue_6) == 0x000760, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetValueAtLevel_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000764, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetValueAtLevel_ReturnValue_7) == 0x000768, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetValueAtLevel_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_BooleanAND_ReturnValue) == 0x00076C, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_SetTimerDelegate_ReturnValue_2) == 0x000770, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_SetTimerDelegate_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_CreateDelegate_OutputDelegate_3) == 0x000778, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000788, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GreaterEqual_IntInt_ReturnValue_1) == 0x000789, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GreaterEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_IsValid_ReturnValue_1) == 0x00078A, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetValueAtLevel_ReturnValue_8) == 0x00078C, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetValueAtLevel_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_SetTimerDelegate_ReturnValue_3) == 0x000790, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_SetTimerDelegate_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_GetValueAtLevel_ReturnValue_9) == 0x000798, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_GetValueAtLevel_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, K2Node_CustomEvent_StopDecalUpdates) == 0x00079C, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::K2Node_CustomEvent_StopDecalUpdates' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x00079D, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, Temp_object_Variable) == 0x0007A0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_SphereOverlapActors_OutActors) == 0x0007B0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_SphereOverlapActors_OutActors' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_SphereOverlapActors_ReturnValue) == 0x0007C0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_SphereOverlapActors_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_Array_Get_Item) == 0x0007C8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_Array_Length_ReturnValue) == 0x0007D0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_MakeHitResult_ReturnValue) == 0x0007D4, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_MakeHitResult_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_Less_IntInt_ReturnValue) == 0x000870, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_IsValid_ReturnValue_2) == 0x000871, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_GetActorLocation_ReturnValue_3) == 0x000874, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_GetActorLocation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_GetActorLocation_ReturnValue_4) == 0x000880, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_GetActorLocation_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_Vector_Distance_ReturnValue) == 0x00088C, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_Vector_Distance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics, CallFunc_K2_GetActorLocation_ReturnValue_5) == 0x000890, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_ExecuteUbergraph_BGA_Athena_ShieldGenerator_NonPhysics::CallFunc_K2_GetActorLocation_ReturnValue_5' has a wrong offset!");

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.HandleBinding
// 0x0010 (0x0010 - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_HandleBinding final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    HitComp;                                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_HandleBinding) == 0x000008, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_HandleBinding");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_HandleBinding) == 0x000010, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_HandleBinding");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_HandleBinding, Actor) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_HandleBinding::Actor' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_HandleBinding, HitComp) == 0x000008, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_HandleBinding::HitComp' has a wrong offset!");

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.OnBuildingActorInitialized
// 0x0002 (0x0002 - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_OnBuildingActorInitialized final
{
public:
	EFortBuildingInitializationReason             InitializationReason;                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortBuildingPersistentState                  BuildingPersistentState;                           // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnBuildingActorInitialized) == 0x000001, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_OnBuildingActorInitialized");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnBuildingActorInitialized) == 0x000002, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_OnBuildingActorInitialized");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnBuildingActorInitialized, InitializationReason) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnBuildingActorInitialized::InitializationReason' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnBuildingActorInitialized, BuildingPersistentState) == 0x000001, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnBuildingActorInitialized::BuildingPersistentState' has a wrong offset!");

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.OnDeathServer
// 0x00F8 (0x00F8 - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer final
{
public:
	float                                         Damage;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  DamageTags;                                        // 0x0008(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FVector                                Momentum;                                          // 0x0028(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitInfo;                                           // 0x0034(0x009C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AController*                            InstigatedBy;                                      // 0x00D0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x00D8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           EffectContext;                                     // 0x00E0(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer) == 0x000008, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer) == 0x0000F8, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer, Damage) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer::Damage' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer, DamageTags) == 0x000008, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer::DamageTags' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer, Momentum) == 0x000028, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer::Momentum' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer, HitInfo) == 0x000034, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer::HitInfo' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer, InstigatedBy) == 0x0000D0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer::InstigatedBy' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer, DamageCauser) == 0x0000D8, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer::DamageCauser' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer, EffectContext) == 0x0000E0, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnDeathServer::EffectContext' has a wrong offset!");

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.OnRep_SetFXMode
// 0x0002 (0x0002 - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_OnRep_SetFXMode final
{
public:
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue_1;        // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnRep_SetFXMode) == 0x000001, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_OnRep_SetFXMode");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnRep_SetFXMode) == 0x000002, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_OnRep_SetFXMode");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnRep_SetFXMode, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnRep_SetFXMode::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_OnRep_SetFXMode, CallFunc_GreaterEqual_IntInt_ReturnValue_1) == 0x000001, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_OnRep_SetFXMode::CallFunc_GreaterEqual_IntInt_ReturnValue_1' has a wrong offset!");

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.PlayHitFX
// 0x009C (0x009C - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_PlayHitFX final
{
public:
	struct FHitResult                             HitResult;                                         // 0x0000(0x009C)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_PlayHitFX) == 0x000004, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_PlayHitFX");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_PlayHitFX) == 0x00009C, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_PlayHitFX");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_PlayHitFX, HitResult) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_PlayHitFX::HitResult' has a wrong offset!");

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.RemoveDecal
// 0x0001 (0x0001 - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_RemoveDecal final
{
public:
	bool                                          StopDecalUpdates;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_RemoveDecal) == 0x000001, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_RemoveDecal");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_RemoveDecal) == 0x000001, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_RemoveDecal");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_RemoveDecal, StopDecalUpdates) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_RemoveDecal::StopDecalUpdates' has a wrong offset!");

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.SetLocationFromServer
// 0x000C (0x000C - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_SetLocationFromServer final
{
public:
	struct FVector                                ServerLocation;                                    // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_SetLocationFromServer) == 0x000004, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_SetLocationFromServer");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_SetLocationFromServer) == 0x00000C, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_SetLocationFromServer");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_SetLocationFromServer, ServerLocation) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_SetLocationFromServer::ServerLocation' has a wrong offset!");

// Function BGA_Athena_ShieldGenerator_NonPhysics.BGA_Athena_ShieldGenerator_NonPhysics_C.Update FX for Water
// 0x0010 (0x0010 - 0x0000)
struct BGA_Athena_ShieldGenerator_NonPhysics_C_Update_FX_for_Water final
{
public:
	class AFortWaterBodyActor*                    Water_Body;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsInWater;                                         // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BGA_Athena_ShieldGenerator_NonPhysics_C_Update_FX_for_Water) == 0x000008, "Wrong alignment on BGA_Athena_ShieldGenerator_NonPhysics_C_Update_FX_for_Water");
static_assert(sizeof(BGA_Athena_ShieldGenerator_NonPhysics_C_Update_FX_for_Water) == 0x000010, "Wrong size on BGA_Athena_ShieldGenerator_NonPhysics_C_Update_FX_for_Water");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_Update_FX_for_Water, Water_Body) == 0x000000, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_Update_FX_for_Water::Water_Body' has a wrong offset!");
static_assert(offsetof(BGA_Athena_ShieldGenerator_NonPhysics_C_Update_FX_for_Water, IsInWater) == 0x000008, "Member 'BGA_Athena_ShieldGenerator_NonPhysics_C_Update_FX_for_Water::IsInWater' has a wrong offset!");

}

