#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CalendarProps_V2

#include "Basic.hpp"

#include "CalendarPropData_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_CalendarProps_V2.BP_CalendarProps_V2_C.Event
// 0x0010 (0x0010 - 0x0000)
struct BP_CalendarProps_V2_C_Event final
{
public:
	class FString                                 EventName_0;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CalendarProps_V2_C_Event) == 0x000008, "Wrong alignment on BP_CalendarProps_V2_C_Event");
static_assert(sizeof(BP_CalendarProps_V2_C_Event) == 0x000010, "Wrong size on BP_CalendarProps_V2_C_Event");
static_assert(offsetof(BP_CalendarProps_V2_C_Event, EventName_0) == 0x000000, "Member 'BP_CalendarProps_V2_C_Event::EventName_0' has a wrong offset!");

// Function BP_CalendarProps_V2.BP_CalendarProps_V2_C.ExecuteUbergraph_BP_CalendarProps_V2
// 0x06F0 (0x06F0 - 0x0000)
struct BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCalendarPropData                      CallFunc_Array_Get_Item;                           // 0x0020(0x0080)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AD[0x3];                                       // 0x00AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Temp_class_Variable;                               // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsActor;                   // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UObject>                    K2Node_CustomEvent_Loaded;                         // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_4;                   // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_5;                   // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F4[0xC];                                       // 0x00F4(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0100(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_GetTransform_ReturnValue_1;               // 0x0130(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetCalendarEventInformation_bIsEventActive; // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x7];                                      // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimespan                              CallFunc_GetCalendarEventInformation_TimeSinceBegin; // 0x0168(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              CallFunc_GetCalendarEventInformation_TimeUntilEnd; // 0x0170(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetCalendarEventInformation_TimeSpanRatio; // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17C[0x4];                                      // 0x017C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item_1;                         // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetArrayElementAttachedTo_AttachToSpawned; // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_189[0x3];                                      // 0x0189(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetArrayElementAttachedTo_ElementToAttachTo; // 0x018C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_GetTransform_ReturnValue_2;               // 0x0190(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C8[0x8];                                      // 0x01C8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeRelativeTransform_ReturnValue;        // 0x01D0(0x0030)(IsPlainOldData, NoDestructor)
	TSoftClassPtr<class UClass>                   CallFunc_Conv_ClassToSoftClassReference_ReturnValue; // 0x0200(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	class AFortEQSPrevisActor*                    K2Node_DynamicCast_AsFort_EQSPrevis_Actor;         // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_231[0x7];                                      // 0x0231(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABuildingSMActor*                       K2Node_DynamicCast_AsBuilding_SMActor;             // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0241(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0242(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_243[0x1];                                      // 0x0243(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0244(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_248[0x8];                                      // 0x0248(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCalendarPropData                      CallFunc_Array_Get_Item_2;                         // 0x0250(0x0080)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x02D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D4[0xC];                                      // 0x02D4(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_ComposeTransforms_ReturnValue;            // 0x02E0(0x0030)(IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0310(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_311[0x7];                                      // 0x0311(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_LoadClassAsset_Blocking_ReturnValue;      // 0x0318(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsActor_1;                 // 0x0320(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_1;                // 0x0328(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_329[0x7];                                      // 0x0329(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0330(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_4;                  // 0x0338(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33C[0x4];                                      // 0x033C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x0340(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x0348(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_2;                  // 0x034C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_351[0x3];                                      // 0x0351(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x0354(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_358[0x8];                                      // 0x0358(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue_3;               // 0x0360(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	struct FCalendarPropData                      CallFunc_Array_Get_Item_3;                         // 0x0390(0x0080)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x0410(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0414(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_415[0xB];                                      // 0x0415(0x000B)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_ComposeTransforms_ReturnValue_1;          // 0x0420(0x0030)(IsPlainOldData, NoDestructor)
	class UClass*                                 CallFunc_LoadClassAsset_Blocking_ReturnValue_1;    // 0x0450(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_EventName;                      // 0x0458(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsActor_2;                 // 0x0468(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_2;                // 0x0470(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_471[0x7];                                      // 0x0471(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1; // 0x0478(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StriStri_ReturnValue;          // 0x0480(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_481[0x7];                                      // 0x0481(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue_1;        // 0x0488(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABuildingActor*                         K2Node_DynamicCast_AsBuilding_Actor;               // 0x0490(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0498(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_499[0x3];                                      // 0x0499(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_3;                  // 0x049C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAsyncAction_AuthorityMatchReady*   CallFunc_MatchReadyAsync_ReturnValue;              // 0x04A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABuildingSMActor*                       CallFunc_Array_Get_Item_4;                         // 0x04A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x04B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B1[0xF];                                      // 0x04B1(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCalendarPropData                      K2Node_MakeStruct_CalendarPropData;                // 0x04C0(0x0080)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_4;                  // 0x0540(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_5;                  // 0x0544(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_5;                  // 0x0548(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54C[0x4];                                      // 0x054C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item_5;                         // 0x0550(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABuildingProp*                          K2Node_DynamicCast_AsBuilding_Prop;                // 0x0558(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0560(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0561(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0562(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_563[0x1];                                      // 0x0563(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x0564(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_6;               // 0x0568(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x056C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_56D[0x3];                                      // 0x056D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0570(0x0010)(ZeroConstructor, NoDestructor)
	struct FCalendarPropData                      CallFunc_Array_Get_Item_6;                         // 0x0580(0x0080)(HasGetValueTypeHash)
	class AActor*                                 CallFunc_Array_Get_Item_7;                         // 0x0600(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0608(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_609[0x7];                                      // 0x0609(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABuildingProp*                          K2Node_DynamicCast_AsBuilding_Prop_1;              // 0x0610(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0618(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_619[0x3];                                      // 0x0619(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(TSubclassOf<class UObject> Loaded)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x061C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_62C[0x4];                                      // 0x062C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item_8;                         // 0x0630(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABuildingProp*                          K2Node_DynamicCast_AsBuilding_Prop_2;              // 0x0638(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0640(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_641[0x3];                                      // 0x0641(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_7;               // 0x0644(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0648(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x0649(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64A[0x6];                                      // 0x064A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCalendarPropData                      CallFunc_Array_Get_Item_9;                         // 0x0650(0x0080)(HasGetValueTypeHash)
	class AActor*                                 CallFunc_Array_Get_Item_10;                        // 0x06D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x06D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D9[0x7];                                      // 0x06D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABuildingProp*                          K2Node_DynamicCast_AsBuilding_Prop_3;              // 0x06E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x06E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2) == 0x000010, "Wrong alignment on BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2");
static_assert(sizeof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2) == 0x0006F0, "Wrong size on BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, EntryPoint) == 0x000000, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Array_Index_Variable_1) == 0x000010, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Array_Index_Variable_2) == 0x000014, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item) == 0x000020, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Length_ReturnValue_1) == 0x0000A0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Length_ReturnValue_2) == 0x0000A4, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Loop_Counter_Variable_1) == 0x0000A8, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x0000AC, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Add_IntInt_ReturnValue_1) == 0x0000B0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Array_Index_Variable_3) == 0x0000B4, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Loop_Counter_Variable_2) == 0x0000B8, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Add_IntInt_ReturnValue_2) == 0x0000BC, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_class_Variable) == 0x0000C0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_class_Variable' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_ClassDynamicCast_AsActor) == 0x0000C8, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_ClassDynamicCast_AsActor' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_ClassDynamicCast_bSuccess) == 0x0000D0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_CustomEvent_Loaded) == 0x0000D8, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Add_ReturnValue) == 0x0000E0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Loop_Counter_Variable_3) == 0x0000E4, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Add_IntInt_ReturnValue_3) == 0x0000E8, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Array_Index_Variable_4) == 0x0000EC, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Array_Index_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Array_Index_Variable_5) == 0x0000F0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Array_Index_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetTransform_ReturnValue) == 0x000100, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetTransform_ReturnValue_1) == 0x000130, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetCalendarEventInformation_bIsEventActive) == 0x000160, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetCalendarEventInformation_bIsEventActive' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetCalendarEventInformation_TimeSinceBegin) == 0x000168, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetCalendarEventInformation_TimeSinceBegin' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetCalendarEventInformation_TimeUntilEnd) == 0x000170, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetCalendarEventInformation_TimeUntilEnd' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetCalendarEventInformation_TimeSpanRatio) == 0x000178, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetCalendarEventInformation_TimeSpanRatio' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item_1) == 0x000180, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetArrayElementAttachedTo_AttachToSpawned) == 0x000188, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetArrayElementAttachedTo_AttachToSpawned' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetArrayElementAttachedTo_ElementToAttachTo) == 0x00018C, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetArrayElementAttachedTo_ElementToAttachTo' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetTransform_ReturnValue_2) == 0x000190, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetTransform_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetObjectClass_ReturnValue) == 0x0001C0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_MakeRelativeTransform_ReturnValue) == 0x0001D0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_MakeRelativeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Conv_ClassToSoftClassReference_ReturnValue) == 0x000200, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Conv_ClassToSoftClassReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_AsFort_EQSPrevis_Actor) == 0x000228, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_AsFort_EQSPrevis_Actor' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_bSuccess) == 0x000230, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_AsBuilding_SMActor) == 0x000238, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_AsBuilding_SMActor' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_bSuccess_1) == 0x000240, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_IsValid_ReturnValue) == 0x000241, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_IsValid_ReturnValue_1) == 0x000242, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Length_ReturnValue_3) == 0x000244, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item_2) == 0x000250, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Length_ReturnValue_4) == 0x0002D0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_ComposeTransforms_ReturnValue) == 0x0002E0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_ComposeTransforms_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Less_IntInt_ReturnValue) == 0x000310, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_LoadClassAsset_Blocking_ReturnValue) == 0x000318, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_LoadClassAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_ClassDynamicCast_AsActor_1) == 0x000320, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_ClassDynamicCast_AsActor_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_ClassDynamicCast_bSuccess_1) == 0x000328, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_ClassDynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000330, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Loop_Counter_Variable_4) == 0x000338, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Loop_Counter_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_FinishSpawningActor_ReturnValue) == 0x000340, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Add_ReturnValue_1) == 0x000348, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Add_ReturnValue_2) == 0x00034C, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Add_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Less_IntInt_ReturnValue_1) == 0x000350, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Add_IntInt_ReturnValue_4) == 0x000354, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_GetTransform_ReturnValue_3) == 0x000360, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_GetTransform_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item_3) == 0x000390, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Length_ReturnValue_5) == 0x000410, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Less_IntInt_ReturnValue_2) == 0x000414, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_ComposeTransforms_ReturnValue_1) == 0x000420, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_ComposeTransforms_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_LoadClassAsset_Blocking_ReturnValue_1) == 0x000450, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_LoadClassAsset_Blocking_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_CustomEvent_EventName) == 0x000458, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_CustomEvent_EventName' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_ClassDynamicCast_AsActor_2) == 0x000468, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_ClassDynamicCast_AsActor_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_ClassDynamicCast_bSuccess_2) == 0x000470, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_ClassDynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1) == 0x000478, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_EqualEqual_StriStri_ReturnValue) == 0x000480, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_EqualEqual_StriStri_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_FinishSpawningActor_ReturnValue_1) == 0x000488, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_FinishSpawningActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_AsBuilding_Actor) == 0x000490, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_AsBuilding_Actor' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_bSuccess_2) == 0x000498, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Add_ReturnValue_3) == 0x00049C, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Add_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_MatchReadyAsync_ReturnValue) == 0x0004A0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_MatchReadyAsync_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item_4) == 0x0004A8, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_IsValid_ReturnValue_2) == 0x0004B0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_MakeStruct_CalendarPropData) == 0x0004C0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_MakeStruct_CalendarPropData' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Add_ReturnValue_4) == 0x000540, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Add_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Add_ReturnValue_5) == 0x000544, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Add_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, Temp_int_Loop_Counter_Variable_5) == 0x000548, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::Temp_int_Loop_Counter_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item_5) == 0x000550, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_AsBuilding_Prop) == 0x000558, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_AsBuilding_Prop' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_bSuccess_3) == 0x000560, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Less_IntInt_ReturnValue_3) == 0x000561, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_IsValid_ReturnValue_3) == 0x000562, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Add_IntInt_ReturnValue_5) == 0x000564, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Length_ReturnValue_6) == 0x000568, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Length_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Less_IntInt_ReturnValue_4) == 0x00056C, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_CreateDelegate_OutputDelegate) == 0x000570, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item_6) == 0x000580, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item_6' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item_7) == 0x000600, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item_7' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Greater_IntInt_ReturnValue) == 0x000608, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_AsBuilding_Prop_1) == 0x000610, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_AsBuilding_Prop_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_bSuccess_4) == 0x000618, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_CreateDelegate_OutputDelegate_1) == 0x00061C, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item_8) == 0x000630, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item_8' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_AsBuilding_Prop_2) == 0x000638, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_AsBuilding_Prop_2' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_bSuccess_5) == 0x000640, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Length_ReturnValue_7) == 0x000644, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Length_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_IsValid_ReturnValue_4) == 0x000648, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Less_IntInt_ReturnValue_5) == 0x000649, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item_9) == 0x000650, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item_9' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Array_Get_Item_10) == 0x0006D0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Array_Get_Item_10' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, CallFunc_Greater_IntInt_ReturnValue_1) == 0x0006D8, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_AsBuilding_Prop_3) == 0x0006E0, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_AsBuilding_Prop_3' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2, K2Node_DynamicCast_bSuccess_6) == 0x0006E8, "Member 'BP_CalendarProps_V2_C_ExecuteUbergraph_BP_CalendarProps_V2::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");

// Function BP_CalendarProps_V2.BP_CalendarProps_V2_C.GetArrayElementAttachedTo
// 0x0080 (0x0080 - 0x0000)
struct BP_CalendarProps_V2_C_GetArrayElementAttachedTo final
{
public:
	class AActor*                                 SpawnedActor;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AttachToSpawned;                                   // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ElementToAttachTo;                                 // 0x000C(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABuildingSMActor*                       K2Node_DynamicCast_AsBuilding_SMActor;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0055(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_56[0x2];                                       // 0x0056(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetDisplayName_ReturnValue_1;             // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo) == 0x000008, "Wrong alignment on BP_CalendarProps_V2_C_GetArrayElementAttachedTo");
static_assert(sizeof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo) == 0x000080, "Wrong size on BP_CalendarProps_V2_C_GetArrayElementAttachedTo");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, SpawnedActor) == 0x000000, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::SpawnedActor' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, AttachToSpawned) == 0x000008, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::AttachToSpawned' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, ElementToAttachTo) == 0x00000C, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::ElementToAttachTo' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, K2Node_DynamicCast_AsBuilding_SMActor) == 0x000010, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::K2Node_DynamicCast_AsBuilding_SMActor' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, Temp_int_Array_Index_Variable) == 0x00001C, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, CallFunc_GetDisplayName_ReturnValue) == 0x000020, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, CallFunc_Concat_StrStr_ReturnValue) == 0x000030, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, Temp_int_Loop_Counter_Variable) == 0x000040, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, CallFunc_Array_Get_Item) == 0x000048, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, CallFunc_Array_Length_ReturnValue) == 0x000050, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000054, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, CallFunc_Less_IntInt_ReturnValue) == 0x000055, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, CallFunc_GetDisplayName_ReturnValue_1) == 0x000058, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::CallFunc_GetDisplayName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, CallFunc_Add_IntInt_ReturnValue) == 0x000068, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CalendarProps_V2_C_GetArrayElementAttachedTo, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000070, "Member 'BP_CalendarProps_V2_C_GetArrayElementAttachedTo::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");

// Function BP_CalendarProps_V2.BP_CalendarProps_V2_C.OnLoaded_641CE9AD409EE6C017B68B9ACFE598F6
// 0x0008 (0x0008 - 0x0000)
struct BP_CalendarProps_V2_C_OnLoaded_641CE9AD409EE6C017B68B9ACFE598F6 final
{
public:
	TSubclassOf<class UObject>                    Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(BP_CalendarProps_V2_C_OnLoaded_641CE9AD409EE6C017B68B9ACFE598F6) == 0x000008, "Wrong alignment on BP_CalendarProps_V2_C_OnLoaded_641CE9AD409EE6C017B68B9ACFE598F6");
static_assert(sizeof(BP_CalendarProps_V2_C_OnLoaded_641CE9AD409EE6C017B68B9ACFE598F6) == 0x000008, "Wrong size on BP_CalendarProps_V2_C_OnLoaded_641CE9AD409EE6C017B68B9ACFE598F6");
static_assert(offsetof(BP_CalendarProps_V2_C_OnLoaded_641CE9AD409EE6C017B68B9ACFE598F6, Loaded) == 0x000000, "Member 'BP_CalendarProps_V2_C_OnLoaded_641CE9AD409EE6C017B68B9ACFE598F6::Loaded' has a wrong offset!");

}

