#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortFeatUpdatesLog

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortFeatUpdatesLog.FortFeatUpdatesLog_C
// 0x0008 (0x0348 - 0x0340)
class UFortFeatUpdatesLog_C final : public UFortQuestUpdatesLog
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_FortFeatUpdatesLog(int32 EntryPoint);
	void CreateAnnouncementUpdate(const class UFortQuestObjectiveInfo* QuestItemToCheck);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortFeatUpdatesLog_C">();
	}
	static class UFortFeatUpdatesLog_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortFeatUpdatesLog_C>();
	}
};
static_assert(alignof(UFortFeatUpdatesLog_C) == 0x000008, "Wrong alignment on UFortFeatUpdatesLog_C");
static_assert(sizeof(UFortFeatUpdatesLog_C) == 0x000348, "Wrong size on UFortFeatUpdatesLog_C");
static_assert(offsetof(UFortFeatUpdatesLog_C, UberGraphFrame) == 0x000340, "Member 'UFortFeatUpdatesLog_C::UberGraphFrame' has a wrong offset!");

}

