#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_WestSausage_WebWasShot

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_WestSausage_WebWasShot.GCN_WestSausage_WebWasShot_C
// 0x0000 (0x0470 - 0x0470)
class AGCN_WestSausage_WebWasShot_C final : public AFortGameplayCueNotify_BurstLatent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_WestSausage_WebWasShot_C">();
	}
	static class AGCN_WestSausage_WebWasShot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_WestSausage_WebWasShot_C>();
	}
};
static_assert(alignof(AGCN_WestSausage_WebWasShot_C) == 0x000008, "Wrong alignment on AGCN_WestSausage_WebWasShot_C");
static_assert(sizeof(AGCN_WestSausage_WebWasShot_C) == 0x000470, "Wrong size on AGCN_WestSausage_WebWasShot_C");

}

