#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Athena_FallDamageImmunity

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_Athena_FallDamageImmunity.GCNL_Athena_FallDamageImmunity_C
// 0x0010 (0x0850 - 0x0840)
class AGCNL_Athena_FallDamageImmunity_C final : public AFortGameplayCueNotifyAthena_FallDamageImmunity
{
public:
	class UAudioComponent*                        InUseLoopAudio;                                    // 0x0840(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Target;                                            // 0x0848(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNL_Athena_FallDamageImmunity_C">();
	}
	static class AGCNL_Athena_FallDamageImmunity_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_Athena_FallDamageImmunity_C>();
	}
};
static_assert(alignof(AGCNL_Athena_FallDamageImmunity_C) == 0x000008, "Wrong alignment on AGCNL_Athena_FallDamageImmunity_C");
static_assert(sizeof(AGCNL_Athena_FallDamageImmunity_C) == 0x000850, "Wrong size on AGCNL_Athena_FallDamageImmunity_C");
static_assert(offsetof(AGCNL_Athena_FallDamageImmunity_C, InUseLoopAudio) == 0x000840, "Member 'AGCNL_Athena_FallDamageImmunity_C::InUseLoopAudio' has a wrong offset!");
static_assert(offsetof(AGCNL_Athena_FallDamageImmunity_C, Target) == 0x000848, "Member 'AGCNL_Athena_FallDamageImmunity_C::Target' has a wrong offset!");

}

