#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_ScorePlacementGeneric

#include "Basic.hpp"

#include "TextStyle_ScorePlacementGold_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-ScorePlacementGeneric.TextStyle-ScorePlacementGeneric_C
// 0x0000 (0x0180 - 0x0180)
class UTextStyle_ScorePlacementGeneric_C final : public UTextStyle_ScorePlacementGold_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-ScorePlacementGeneric_C">();
	}
	static class UTextStyle_ScorePlacementGeneric_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_ScorePlacementGeneric_C>();
	}
};
static_assert(alignof(UTextStyle_ScorePlacementGeneric_C) == 0x000010, "Wrong alignment on UTextStyle_ScorePlacementGeneric_C");
static_assert(sizeof(UTextStyle_ScorePlacementGeneric_C) == 0x000180, "Wrong size on UTextStyle_ScorePlacementGeneric_C");

}

